### ISSUE TITLE
homepage navbar changes

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#13]
![homepage-navbar-changes](https://user-images.githubusercontent.com/4512335/52629056-80867b00-2eeb-11e9-8c82-4bce0a8fd084.png)

actually, let's just update the navbar for now (i'll just keep occasionally adding featured articles manually). once the main author page functionalities are implemented, we can then updated the homepage to display recent articles from the DB (rather than pulling from the HTML).

- "Replications" link (http://curatescience.org/replications.html) moved within the left-opening drawer
- logged-in users can click "Create author page" to create their own article list (this becomes "My author page" once an author page exists, which will bring the user to their author page/article list)

admin users will have the following additional capacities:
- to create additional new author pages
- add new articles not yet associated with an author page
- invite new users so that they can create their own author page. see #14 for details.

**Comment by onejgordon** [comment]
@alexkyllo I've seen the Author.slug field, but can you clarify how I should lookup author from user model? We'll need to do this upon signin to display links to "go to my author page" or "create author page".

Should this be a static method of Author (e.g. `GetByUser(user)`), or is there another way?

**Comment by alexkyllo** [comment]
I haven't gotten to that item yet--I will be adding an API endpoint to get a user account, which will have the related author object nested in it, if exists. As well as a create author endpoint that has a username property so you can link them.

**Comment by alexkyllo** [comment]
Ok, I pushed a change to the `redo` branch. I haven't written tests for it yet but now the /api/accounts/<username>/ endpoint should show the author object nested in it if there is one, and the /api/authors/<slug>/ endpoint includes an "account": "<username>" property.

**Comment by onejgordon** [comment]
Thanks @alexkyllo -- I realized the django login flow is a little opaque to me. What we ultimately need to support author page management is to be able to get access to the author object (if one is linked to the signed in user) upon login, and read and write to it (when changes are made) in a request handler.

Traditionally (e.g. in app engine standard) this would be done in the session, or as a member of the request object. In django, what's the best practice? At what point in the flow should we be calling the `
/api/accounts/<username>/` endpoint to save author data to the session?

**Comment by alexkyllo** [comment]
Django's request object is pretty powerful, within a view controller function we can do 
`request.user`, `if request.user.is_authenticated:`, `if hasattr(request.user, 'author'):`, `request.user.author.slug`, etc.

Since `Author` has a one-to-one relationship to `User`, it can be accessed with the `.author` property of the `User` object in our Python code (it throws an exception if there is no author linked, hence the use of `hasattr` as a guard).

I was utilizing the stock login/logout views in `django.contrib.auth.views`: which are documented here: https://docs.djangoproject.com/en/2.1/topics/auth/default/#all-authentication-views but those are designed for HTML form-based login/logout. If you're going to be implementing those via REST I will need to add equivalent views for that. I might use this package: https://github.com/Tivix/django-rest-auth

**Comment by onejgordon** [comment]
Got it, thanks, that works.

In my opinion keeping the login page as a standard HTML-rendered view should be fine, so let's stick with that for now.

**Comment by eplebel** [comment]
this is working in staging (https://curatescience-staging.appspot.com/app/), but i'm keeping it open because i still need to test that a non-admin user cannot execute admin actions (which i cannot yet test because "invite user" functionality not yet working).
