### ISSUE TITLE
add Lightbox media viewer to view key figures/tables

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#34]
the fancier FancyBox media viewer is definitely preferred for various reasons (see [here](https://github.com/ScienceCommons/curate_science/issues/22#issuecomment-473543028)), but for now let's just use [Lightbox](https://frontend-collective.github.io/react-image-lightbox/)

copied over from #22

**Comment by onejgordon** [comment]
The current CS author pages such as [etienne's](http://curatescience.org/author/etienne.lebel.html) demonstrate that the lightbox, when opened, is a slideshow of all figures across all articles on that author's page.

If this cross-article viewing functionality is required at this stage, I think we'll need to reconsider and possibly adjust the API. Currently figure data doesn't get downloaded until user opens the article editor modal, or clicks the 'more' link in the article list. This is because the article objects returned from the list endpoint `list_articles_for_author` do not contain KeyFigure data.

Possible resolutions:

1. Return all key figures in `list_articles_for_author` endpoint (may be performance considerations)
2. Add logic to slideshow viewer to fetch figures for next article, iteratively, as user moves through slideshow (this is a non-trivial amount of UI-side work)
3. Adjust requirement such that each slideshow that appears includes only figures in that article

@alexkyllo any options I'm missing?

**Comment by eplebel** [comment]
> If this cross-article viewing functionality is required at this stage, I think we'll need to reconsider and possibly adjust the API.

no let's just punt on cross-article media viewing for now.

(as long as one can view a slideshow of *all* figures across a specific article; currently on staging, one can only view 1 figure at a time, though perhaps this is just a temporary WIP thing.)

**Comment by onejgordon** [comment]
> currently on staging, one can only view 1 figure at a time, though perhaps this is just a temporary WIP thing

Yeah, paused work until I knew which direction we were going. Working on enabling all figures per article now.
