### ISSUE TITLE
article list stylistic issues (medium priority)

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#37]
medium priority article list stylistic issues to be fixed for MVP (early beta testers):

- [x] peer review information all on the same (rather than separate) line
- [x] author_contributions, competing_interests, and funding_sources should be trimmed beyond ~85 characters (rather than 500)
- [x] larger (down-arrow) expand button (should be at least 32 x 32px)

moved from #23

**Comment by onejgordon** [comment]
> peer review information all on the same (rather than separate) line

I've done this, but am now considering how to mitigate a likely edge case where the peer review link intersects with the action buttons. 

<img width="688" alt="Screen Shot 2019-03-25 at 1 26 51 PM" src="https://user-images.githubusercontent.com/57584/54940813-dd6d4c00-4f01-11e9-9f44-73360519bc14.png">

A couple of options, I'm sure there are many others:

1. Move action buttons outside the card (e.g. to the right) so that no content overlap is possible
2. Make action buttons smaller to reduce the chances of (but not eliminate) this kind of overlap

**Comment by eplebel** [comment]
> A couple of options, I'm sure there are many others:
Move action buttons outside the card (e.g. to the right) so that no content overlap is possible
Make action buttons smaller to reduce the chances of (but not eliminate) this kind of overlap

ya we can just postpone fixing this for now given open peer review links are still pretty rare.

but yes my preference would be for action buttons to be outside the card (as they were in the specs/wire frames), but there are tons of higher-priority issues to deal with right now.
