### ISSUE TITLE
non-admin users can't cancel out of new article modal after waiting longer than ~1 second

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#41]
steps:
1. as non-admin user, click "Add article"
2. wait ~1 second
3. click cancel
notice nothing happens and one cannot cancel out of modal window (must reload the page to continue, which will bring you back to author page)

additional info:
- can cancel right away, but not after brief moment of about ~1 second
- it happens whether text is entered or not
- it does *not* happen if editing pre-existing article (i.e., edit pre-existing article, wait more than ~1 second, notice *can* cancel out of modal) 

somehow this only happens for non-admin users, so i suspect this is related to setting articles as live/non-live.

**Comment by onejgordon** [comment]
Looked into this, and it is a side-effect of our chosen approach related to when to create the article in the db. We decided upon a flow where:

1. User clicks "add article" and new placeholder article is immediately created in db (but not yet marked live)
2. User makes edits to form
3. If user cancels at this point, we try to delete the article before closing dialog
4. If user saves at this point, we make the updates to the article and mark it as live

The `delete_article` endpoint is an admin only resource currently, which was also agreed upon. Unfortunately, this means non-admin users can't delete their own partially created (not yet live) articles, which currently results in an error preventing dialog from closing.

Options I can see are:

- Allow non-admin users to delete their own articles when not `is_live`
- Just leave the non-live articles in the db (they wont appear on author pages since we filter for that). This would result in a lot of extraneous articles in db.
- Re-think deletion on cancel flow

Thoughts? 

@alexkyllo may have additional ideas on API-based resolutions.

**Comment by eplebel** [comment]
> Allow non-admin users to delete their own articles when not is_live

i'd say option 1 is probably easiest/best for now.

**Comment by alexkyllo** [comment]
This opens a can of worms. From an API permissions perspective, since users can edit their articles, they can edit `is_live`, so they can delete their articles by flipping `is_live` to false first. So it's simpler and more consistent to just give users permission to delete their articles via the API. But the ability to delete "their" articles also means they can delete any article by linking it to their author page first.

So, if we allow users to delete articles via the API in this special case, then they can delete any article in the system.

You can say that the UI just won't give them a way to do that, but there's absolutely nothing stopping users from making API calls if they know how to.

**Comment by onejgordon** [comment]
Maybe not the cleanest solution, but might this work?

Adjust API to allow deletion of an article only if either of the two conditions is met:
- User is admin
- User is sole author of article

This would only disallow the 'delete any article' hack you raised if users are also disallowed from ever removing other authors from an article, but since we have the link/unlink API endpoint now, this seems doable.

**Comment by eplebel** [comment]
this sounds reasonable to me 
(and just to make sure i'm understanding your last sentence:  non-admin users *cannot* unlink articles from another user's author page, which avoids the problem Alex mentions where a non-admin user could delete any article in the system)

**Comment by eplebel** [comment]
@alexkyllo any thoughts on this? (either way, could you work on this next?)

**Comment by alexkyllo** [comment]
Yeah this sounds OK, I'll pick it up next

**Comment by alexkyllo** [comment]
Just pushed a change to staging for this. Now both admins and users who are the only author linked to the article, can delete a given article. If a user tries to delete an article where they're not the only author, the API will return `405 Method Not Allowed`.

**Comment by eplebel** [comment]
great, this seems to be working, so will close this issue for now.
