### ISSUE TITLE
non-admin users cannot delete figure

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#47]
non-admin users cannot delete added figures. attempting to do so yields `server responded with a status of 403 ()`

this was definitely working before, but i'm not sure when it stopped working.

admin users still *can* delete added figures

**Comment by alexkyllo** [comment]
I think you recall it working before because you were logged in as an admin user at the time.

This line prevents non-admins from deleting key figures, and it hasn't changed since we started the rewrite in February:

https://github.com/ScienceCommons/curate_science/blob/7fa340216fcf49094fc270c9be6874711898ba46/curate/views_api.py#L339

Do you want any authenticated user to be able to delete any key figure?

**Comment by onejgordon** [comment]
I assume we'll want similar logic to article deletion (non-admins can delete figures for articles they're an author of), though we need to decide, once again, if they should have permission for articles:

1. Where they are the only author
2. Where they are among multiple authors

**Comment by eplebel** [comment]
ah ok, ya that's correct, somehow i mis-remembered this. 

i guess we'll have to make a slight tweak in the [basic help guide](https://curate-science-216207.appspot.com/app/help). i.e.,
change
"To delete an added figure, click on the image thumbnail of the figure you want to delete."

to

"To delete an added figure, click on the image thumbnail of the figure you want to delete (administrator users only)."
