### ISSUE TITLE
figures suddenly being displayed in reverse order - on both staging & production!

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#98]
figures being displayed in reverse order, i.e., from last added to first added  instead of from first added to last added

this just changed within the last day or so, and very weird that it's happening on both staging and production.

the only thing i can think of is this automatic bump of django from 2.1.7 to 2.2.10, which appears to have happened within the last 24 hours:
 dependabot/pip/django-2.2.10 Bump django from 2.1.7 to 2.2.10
https://travis-ci.org/ScienceCommons/curate_science/builds/649186092

is there a way to prevent these automatic version bumps, so we can avoid this kind of problem in the future?

(i spent lots of precious time realizing it was happening on *BOTH* staging and production, at which point i looked at the builds, and found this automatic bump potential culprit @$@$%#%$$%)

**UPDATE**: OK i think i've successfully opted-out of automatic security updates bumps for both my user account and the curate science organization repos, following these instructions: https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates

**UPDATE#2**: Is there a way to revert back to django 2.1.7 temporarily, so that we can fix the issue later (if it is in fact django 2.2.10 causing the figure order issue)??

**Comment by mickaobrien** [comment]
@eplebel Just taking a look at this now. I don't think it's related to the dependabot stuff — as far as I can see that opens a PR with the suggested update (e.g. this [Django update PR](https://github.com/ScienceCommons/curate_science/pull/97)) but if it's not merged then nothing happens. The build for it was run automatically when the PR was created to see if there would be any issues merging it but if you look at the `requirements.txt` file ([master](https://github.com/ScienceCommons/curate_science/blob/master/requirements.txt#L8)/[staging](https://github.com/ScienceCommons/curate_science/blob/staging/requirements.txt#L8)) you can see that the version of Django being used is still `2.1.7`.

I *think* the issue is due to the fact that no order is specified when fetching the key figures. Why it worked as expected until now and then decided to reverse it, I'm not sure, maybe there's something else going on... I've pushed a commit (3fdc41b292c72e8d4cd2482eac1c69f989d414c0) that forces the figures to be ordered by ID which should correspond with the order they were added. That fixed it for any articles I found with reversed images (e.g. [this one](https://curate-science-staging-2.appspot.com/app/article/530)). Could you take a look at staging and see if it's working for you? Or if it's all just random trickery!

**Comment by eplebel** [comment]
wow, even weirder. but your latest commit (https://github.com/ScienceCommons/curate_science/commit/3fdc41b292c72e8d4cd2482eac1c69f989d414c0) seems to have fixed it.  all figures are now in the correct order. and i even tested adding new articles, and adding new figures in different orders, and do seem to remain in the correct order, so a million thanks!
especially for the quick turn around on this, pretty impressive stuff.

so figure order is still wrong on production, but i guess when we'll push all of the new changes, which should be very soon, it should fix it.

or if it's not too much trouble, i guess you could push the latest commit (https://github.com/ScienceCommons/curate_science/commit/3fdc41b292c72e8d4cd2482eac1c69f989d414c0) as a hot fix into production, thanks!!
